#!/bin/sh
set -e

cd server
    npx vlserver compile
    tsc
    npx vlquery compile
cd ..

cd client
    tsc
    npx vldom compile

    cd assets
        sass main.scss ../dist/styles.css
    cd ..
cd ..