#!/bin/sh
set -e

cd server
    tsc-watch --noClear --onSuccess "npx vlquery compile" &
cd ..

cd client
    tsc-watch --noClear --onSuccess "npx vldom compile" &

    cd assets
        nodemon -e scss -x "sass styles.scss ../dist/styles.css"
    cd ..
cd ..

cd server
    PGHOST=$${{dbServer}} PGUSER=$${{dbName}} PGPASSWORD=$${{dbName}} PGDATABASE=$${{dbName}} nodemon dist/main.js
cd ..